apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hub-uploads.fullname" . }}
data:
  {{- with .Values.environment }}
  PORT: {{ .port | quote }}
  IRYS_GATEWAY: {{ .irysGateway | quote }}
  IRYS_URL: {{ .irysUrl | quote }}
  {{- end }}
