apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hub-uploads.fullname" . }}
data:
  {{- with .Values.environment }}
  PORT: {{ .port | quote }}
  WEB3_UP_GATEWAY: {{ .web3UpGateway | quote }}
  {{- end }}
