{{- with .Values.secrets }}
{{- if .enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hub-uploads.fullname" $ }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  SOLANA_KEYPAIR: {{ .entries.solanaKeypair | b64enc }}
  SOLANA_RPC_URL: {{ .entries.solanaRpcUrl | b64enc }}
  ARWEAVE_PRIVATE_KEY: {{ .entries.arweavePrivateKey | b64enc }}
{{- end }}
{{- end }}
