{{- with .Values.secrets }}
{{- if .enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hub-uploads.fullname" $ }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  WEB3_UP_KEY: {{ .entries.web3UpKey | b64enc }}
  WEB3_UP_PROOF: {{ .entries.web3UpProof | b64enc }}
{{- end }}
{{- end }}
