hubNamespace: default
domain: 127.0.0.1.nip.io
port: 9080
sessionCookieName: "hub_session"

routes:
- name: api
  serviceName: hub-orgs
  servicePort: 80
  subdomain: api
  paths:
    - /v1/organization
    - /v1/organizations
    - /v1/projects
    - /v1/projects/*
    - /v1/affiliations
    - /v1/members
    - /v1/credentials
    - /v1/credentials/*
    - /v1/webhook/events
    - /v1/webhooks/*
    - /v1/members
    - /v1/members/*
    - /v1/invites
    - /v1/invites/*
  methods:
    - GET
    - POST
    - DELETE
  require_auth: true
  require_org: true
  policy: "hub/api/orgs"

- name: hub-browser-api
  serviceName: hub-orgs
  servicePort: 80
  subdomain: hub
  paths:
    - /browser/login
    - /browser/organizations/*
  methods:
    - POST
  require_auth: true

- name: ui-private
  subdomain: hub
  serviceName: hub
  servicePort: 80
  require_auth: true
  require_org: true
  methods:
    - GET
  paths:
    - /organization/*
    - /projects/*

- name: ui-public
  subdomain: hub
  serviceName: hub
  servicePort: 80
  methods:
    - GET
    - POST
  paths:
    - /
    - /registration
    - /verification
    - /login
    - /recovery
    - /holaplex.svg
    - /_next/static/*
    - /__nextjs_original-stack-frame
    - /api/.ory/*

apisixPlugins:
  kratos:
    serviceName: kratos-public
    servicePort: 80
    files:
      - plugins/kratos.lua
  hubOrgs:
    serviceName: hub-orgs
    servicePort: 80
    files:
      - plugins/hub-orgs.lua
  opa:
    image: openpolicyagent/opa:0.48.0-rootless
    s3:
      bucketUrl: "http://your-bucket-url.s3.us-east-1.amazonaws.com"
      region: us-east-1
      accessKey: ""
      secretKey: ""
    serviceName: opa
    servicePort: 8181
    files:
      - plugins/opa-helper.lua
      - plugins/opa-mod.lua

apisix:
  enabled: true
  fullnameOverride: apisix
  apisix:
    enabled: true
    image:
      repository: apache/apisix
      pullPolicy: IfNotPresent
      tag: 3.1.0-debian
    timezone: "UTC"
    enableIpv6: false
    httpRouter: radixtree_uri

  ingress-controller:
    enabled: true
    fullnameOverride: apisix-ingress-controller
    config:
      apisix:
        serviceName: apisix-admin
        serviceNamespace: ingress-apisix
        adminKey: c2IhapSVZaguYfqfyvcN6RTkeTPinI

  gateway:
    type: NodePort
    externalTrafficPolicy: Cluster
    http:
      enabled: true
      servicePort: 80
      containerPort: 9080
    stream:
      enabled: true
      only: false
      tcp:
        - 9100
      udp:
        - 9200

  admin:
    enabled: true
    type: ClusterIP
    allow:
      ipList:
        - 127.0.0.1/24
        - 10.0.0.0/8
        - 0.0.0.0/0
    port: 9180
    servicePort: 9180
    cors: true
    credentials:
      admin: c2IhapSVZaguYfqfyvcN6RTkeTPinI
      viewer: VduoK1H4ujZB4nus9QEfOjgUjTGkmB

  plugins:
    - kratos
    - opa-mod
    - hub-orgs
    - mocking
    - redirect
    - serverless-pre-function
    - serverless-post-function
    - proxy-rewrite
    - response-rewrite

  customPlugins:
    enabled: true
    plugins:
      - name: "kratos"
        configMap:
          name: "apisix-custom-plugins"
          mounts:
            - key: "kratos.lua"
              path: "/opts/custom_plugins/apisix/plugins/kratos.lua"
            - key: "hub-orgs.lua"
              path: "/opts/custom_plugins/apisix/plugins/hub-orgs.lua"
            - key: "opa-mod.lua"
              path: "/opts/custom_plugins/apisix/plugins/opa-mod.lua"
            - key: "opa-helper.lua"
              path: "/opts/custom_plugins/apisix/plugins/opa-mod/helper.lua"

  logs:
    enableAccessLog: true
    accessLog: "/dev/stdout"
    access_log_format: |-
            {"@timestamp": "$time_iso8601", "client_ip": "$remote_addr", "status": "$status", "referer": "$http_referer" "upstream": "$upstream_scheme://$upstream_host$upstream_uri", "upstream_response_time": "$upstream_response_time"}
    accessLogFormatEscape: json
    errorLog: "/dev/stderr"
    errorLogLevel: "warn"

  etcd:
    enabled: true
    fullnameOverride: apisix-etcd
    image:
      repository: bitnami/etcd
      pullPolicy: IfNotPresent
      tag: 3.5.7-debian-11-r3
    persistence:
      storageClass: "hostpath"
      size: 1Gi
    replicaCount: 1
    host:
      - http://apisix-etcd:2379
    prefix: "/apisix"
    timeout: 30
