hubNamespace: default
domain: 127.0.0.1.nip.io
port: 9080
sessionCookieName: 'hub_session'
loginUri: 'http://hub.127.0.0.1.nip.io:9080/login'
forceVerification: false
verificationUri: 'http://hub.127.0.0.1.nip.io:9080/verification'

maintenanceMode:
  enabled: false

internalService:
  enabled: true

networkPolicies:
  enabled: false

routes:
  - name: api
    serviceName: federated-router
    servicePort: 80
    subdomain: api
    paths:
      - /graphql
    methods:
      - POST
      - OPTIONS
    oauth2:
      enabled: true
    authz:
      enabled: true
      policy: 'hub/graphql/main'
    orgLookup:
      enabled: true
    credits:
      enabled: true
    regexUri:
      - '/graphql'
      - '/'

  - name: api-internal
    serviceName: federated-router
    servicePort: 80
    host: apisix-gateway-internal.ingress-apisix.svc.cluster.local
    paths:
      - /graphql
    methods:
      - POST
      - OPTIONS
    session:
      enabled: true
    authz:
      enabled: true
      policy: 'hub/graphql/main'
    orgLookup:
      enabled: true
    credits:
      enabled: true
    regexUri:
      - '/graphql'
      - '/'

  - name: hub-browser-graphql
    serviceName: federated-router
    servicePort: 80
    subdomain: hub
    paths:
      - /graphql
    methods:
      - POST
      - OPTIONS
    session:
      enabled: true
    sessionJson:
      enabled: true
    authz:
      enabled: true
      policy: 'hub/graphql/main'
    orgLookup:
      enabled: true
    credits:
      enabled: true
    regexUri:
      - '/graphql'
      - '/'

  - name: hub-orgs-browser-api
    serviceName: hub-orgs
    servicePort: 80
    subdomain: hub
    paths:
      - /browser/login
      - /browser/organizations/*
    methods:
      - POST
    session:
      enabled: true
    sessionRedirect:
      enabled: false

  - name: ui-private
    subdomain: hub
    serviceName: hub-ui
    servicePort: 80
    session:
      enabled: true
    sessionRedirect:
      enabled: true
    methods:
      - GET
    paths:
      - /settings
      - /profile/edit
      - /profile/password/edit
      - /webhooks
      - /webhooks/*
      - /members
      - /members/*
      - /organizations
      - /organizations/*
      - /projects
      - /projects/*
      - /treasuries
      - /treasuries/*
      - /credentials
      - /credentials/*
      - /credits
      - /credits/*

  - name: ui-private-invite
    subdomain: hub
    serviceName: hub-ui
    servicePort: 80
    session:
      enabled: true
    sessionRedirect:
      enabled: true
      redirectTo: true
    methods:
      - GET
    paths:
      - /invites/*

  - name: ui-public
    subdomain: hub
    serviceName: hub-ui
    servicePort: 80
    websocket: true
    methods:
      - GET
      - POST
    paths:
      - /
      - /registration
      - /verification
      - /login
      - /recovery
      - /recovery/code
      - /recovery/reset
      - /holaplex.svg
      - /holaplex-small.svg
      - /_next/static/*
      - /_next/webpack-hmr
      - /__nextjs_original-stack-frame
      - /favicon.ico
      - /terms-of-service
      - /privacy-policy
      - /api/.ory/*
      - /api/uploads

  - name: hub-auth-api
    serviceName: hydra-public
    servicePort: 4444
    subdomain: api
    paths:
      - /auth
    methods:
      - POST
    regexUri:
      - '/auth'
      - '/oauth2/token'

  - name: hub-ui-browser-api
    serviceName: hub-ui
    servicePort: 80
    subdomain: hub
    session:
      enabled: true
    paths:
      - /api/credits/purchase
    methods:
      - POST

  - name: hub-credits-webhooks
    subdomain: hub
    serviceName: hub-credits
    servicePort: 80
    methods:
      - POST
    paths:
      - /webhooks/stripe

  - name: hub-nfts-polygon-webhooks
    subdomain: hub
    serviceName: hub-nfts-polygon
    servicePort: 80
    methods:
      - POST
    paths:
      - /webhooks/polygon
    regexUri:
      - '/webhooks/polygon'
      - '/'

  - name: hub-identity-self-service
    serviceName: hub-ui
    servicePort: 80
    subdomain: hub
    paths:
      - /id
      - /id/*
    methods:
      - GET
    regexUri:
      - "^/id/(.*)"
      - "/api/.ory/${1}"

apisixPlugins:
  session:
    serviceName: kratos-public
    servicePort: 80
    files:
      - plugins/session.lua
  oauth2:
    serviceName: hydra-admin
    servicePort: 4445
    files:
      - plugins/oauth2.lua
  sessionRedirect:
    files:
      - plugins/session-redirect.lua
  sessionJson:
    files:
      - plugins/session-json.lua
  authz:
    serviceName: hub-permissions
    servicePort: 80
    files:
      - plugins/authz.lua
      - plugins/authz-helper.lua
  credits:
    serviceName: hub-credits
    servicePort: 80
    files:
      - plugins/credits.lua
  orgLookup:
    query:
      cookieName: '_hub_org'
      headerName: 'X-Client-Owner-Id'
    output:
      headerName: 'X-Organization-Id'
    files:
      - plugins/org-lookup.lua

apisix:
  enabled: true
  fullnameOverride: apisix
  apisix:
    enabled: true
    image:
      repository: apache/apisix
      pullPolicy: IfNotPresent
      tag: 3.3.0-debian
    timezone: 'UTC'
    enableIpv6: false
    httpRouter: radixtree_uri

  ingress-controller:
    enabled: true
    fullnameOverride: apisix-ingress-controller
    config:
      apisix:
        serviceName: apisix-admin
        serviceNamespace: ingress-apisix
        adminKey: c2IhapSVZaguYfqfyvcN6RTkeTPinI

  gateway:
    type: NodePort
    externalTrafficPolicy: Cluster
    http:
      enabled: true
      servicePort: 80
      containerPort: 9080
    tls:
      enabled: false
      servicePort: 443
      containerPort: 9080
    stream:
      enabled: false
      only: false
      tcp: []
      # - 9100
      udp: []
      # - 9200

  admin:
    enabled: true
    type: ClusterIP
    allow:
      ipList:
        - 127.0.0.1/24
        - 10.0.0.0/8
        - 0.0.0.0/0
    port: 9180
    servicePort: 9180
    cors: true
    credentials:
      admin: c2IhapSVZaguYfqfyvcN6RTkeTPinI
      viewer: VduoK1H4ujZB4nus9QEfOjgUjTGkmB

  plugins:
    - mocking
    - cors
    - request-id
    - redirect
    - serverless-pre-function
    - serverless-post-function
    - proxy-rewrite
    - response-rewrite

  customPlugins:
    enabled: true
    plugins:
      - name: 'session'
        configMap:
          name: 'session-plugin'
          mounts:
            - key: 'session.lua'
              path: '/opts/custom_plugins/apisix/plugins/session.lua'
      - name: 'oauth2'
        configMap:
          name: 'oauth2-plugin'
          mounts:
            - key: 'oauth2.lua'
              path: '/opts/custom_plugins/apisix/plugins/oauth2.lua'
      - name: 'session-redirect'
        configMap:
          name: 'session-redirect-plugin'
          mounts:
            - key: 'session-redirect.lua'
              path: '/opts/custom_plugins/apisix/plugins/session-redirect.lua'
      - name: 'session-json'
        configMap:
          name: 'session-json-plugin'
          mounts:
            - key: 'session-json.lua'
              path: '/opts/custom_plugins/apisix/plugins/session-json.lua'
      - name: 'authz'
        configMap:
          name: 'authz-plugin'
          mounts:
            - key: 'authz.lua'
              path: '/opts/custom_plugins/apisix/plugins/authz.lua'
            - key: 'authz-helper.lua'
              path: '/opts/custom_plugins/apisix/plugins/authz/helper.lua'
      - name: 'credits'
        configMap:
          name: 'credits-plugin'
          mounts:
            - key: 'credits.lua'
              path: '/opts/custom_plugins/apisix/plugins/credits.lua'
      - name: 'org-lookup'
        configMap:
          name: 'org-lookup-plugin'
          mounts:
            - key: 'org-lookup.lua'
              path: '/opts/custom_plugins/apisix/plugins/org-lookup.lua'

  logs:
    enableAccessLog: true
    accessLog: '/dev/stdout'
    access_log_format: |-
      {"@timestamp": "$time_iso8601", "client_ip": "$remote_addr", "status": "$status", "referer": "$http_referer" "upstream": "$upstream_scheme://$upstream_host$upstream_uri", "upstream_response_time": "$upstream_response_time"}
    accessLogFormatEscape: json
    errorLog: '/dev/stderr'
    errorLogLevel: 'warn'

  etcd:
    enabled: true
    fullnameOverride: apisix-etcd
    image:
      repository: bitnami/etcd
      pullPolicy: IfNotPresent
      tag: 3.5.8
    persistence:
      size: 1Gi
    replicaCount: 1
    host:
      - http://apisix-etcd:2379
    prefix: '/apisix'
    timeout: 30
