{{- $apisixPlugins := .Values.apisixPlugins -}}
{{- $namespace := .Values.hubNamespace -}}
{{- $domain := .Values.domain -}}
{{- $sessionCookie := .Values.sessionCookieName -}}
{{- $loginUri := .Values.loginUri -}}
{{- with .Values.routes }}
{{- range . }}
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: {{ .name }}
  namespace: {{ $namespace }}
  labels:
    {{- include "hub-gateway.labels" $ | nindent 4 }}
spec:
  http:
  - name: {{ .name }}
    backends:
    - serviceName: {{ .serviceName }}
      servicePort: {{ .servicePort }}
    websocket: {{ .websocket | default false }}
    match:
      hosts:
        - {{ .host | default (printf "%s.%s" .subdomain $domain) | quote }}
      paths:
      {{- .paths | toYaml | nindent 8 }}
      methods:
      {{- .methods | toYaml | nindent 8 }}
    plugins:
    {{- with .session }}
    {{- if .enabled | default false }}
    - name: session
      enable: true
      config:
        host: {{ print "http://" $apisixPlugins.session.serviceName  "." $namespace ".svc:" $apisixPlugins.session.servicePort | quote }}
        expose_user_id: true
        session_cookie_name: {{ $sessionCookie }}
    {{- end }}
    {{- end }}
    {{- with .oauth2 }}
    {{- if .enabled | default false }}
    - name: oauth2
      enable: true
      config:
        host: {{ print "http://" $apisixPlugins.oauth2.serviceName  "." $namespace ".svc:" $apisixPlugins.oauth2.servicePort | quote }}
        expose_client_id: true
        expose_owner: true
    {{- end }}
    {{- end }}
    {{- with .sessionRedirect }}
    {{- if .enabled }}
    - name: session-redirect
      enable: true
      config:
        login_uri: {{ $loginUri }}
        redirect_to: {{ .redirectTo | default false }}
    {{- end }}
    {{- end }}
    {{- with .authz }}
    {{- if .enabled }}
    - name: authz 
      enable: true
      config:
        host: {{ print "http://" $apisixPlugins.authz.serviceName  "." $namespace ".svc:" $apisixPlugins.authz.servicePort | quote }}
        policy: {{ .policy }}
        keto_endpoint: {{ print "http://" $apisixPlugins.authz.serviceName  "-keto-read." $namespace ".svc:" $apisixPlugins.authz.servicePort | quote }}
        with_route: false
        with_service: false
        with_consumer: false
    {{- end }}
    {{- end }}
    {{- if .regexUri }}
    - name: proxy-rewrite
      enable: true
      config:
        regex_uri: 
        {{- .regexUri | toYaml | nindent 10 }}
    {{- end }} 
---
{{- end }}
{{- end }}
