{{- $apisixPlugins := .Values.apisixPlugins -}}
{{- $namespace := .Values.hubNamespace -}}
{{- $domain:= .Values.domain -}}
{{- $sessionCookie := .Values.sessionCookieName -}}
{{- with .Values.routes }}
{{- range . }}
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: {{ .name }}
  namespace: {{ $namespace }}
  labels:
    {{- include "hub-gateway.labels" $ | nindent 4 }}
spec:
  http:
  - name:  {{ .name }}
    backends:
    - serviceName: {{ .serviceName }}
      servicePort: {{ .servicePort }}
    match:
      hosts:
      - {{ print .subdomain "." $domain | quote}}
      paths:
      {{ .paths | toYaml | nindent 7 }}
      methods:
      {{ .methods | toYaml | nindent 7 }}
    plugins:
    {{- if .require_auth}}
    - name: kratos
      enable: true
      config:
        host: {{ print "http://" $apisixPlugins.kratos.serviceName  "." $namespace ".svc:" $apisixPlugins.kratos.servicePort | quote }}
        expose_user_data: true
        expose_user_id: true
        session_cookie_name: {{ $sessionCookie }}
    - name: hub-orgs
      enable: true
      config:
        host: {{ print "http://" $apisixPlugins.hubOrgs.serviceName  "." $namespace ".svc:" $apisixPlugins.hubOrgs.servicePort "/v1" | quote }}
    {{ end }}
    {{- if .regex_uri}}
    - name: proxy-rewrite
      enable: true
      config:
        headers:
        {{ .headers | toYaml | nindent 9 }}
        regex_uri: 
        {{ .regex_uri | toYaml | nindent 9 }}
    {{ end }} 
    {{- if .policy}}
    - name: opa-mod
      enable: true
      config:
        host: {{ print "http://" $apisixPlugins.opa.serviceName  "." $namespace ".svc:" $apisixPlugins.opa.servicePort | quote }}
        policy: {{ .policy }}
        extra_inputs: true
        inputs:
          user_data: $kratos_user_data
          org_id: $org_id
          project_id: $project_id
          affiliations: $hub_affiliations
    {{ end }}
---
{{- end }}
{{- end }}
