{{- $apisixPlugins := .Values.apisixPlugins -}}
{{- $namespace := .Values.hubNamespace -}}
{{- $domain:= .Values.domain -}}
{{- $sessionCookie := .Values.sessionCookieName -}}
{{- with .Values.routes }}
{{- range . }}
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: {{ .name }}
  namespace: {{ $namespace }}
  labels:
    {{- include "hub-gateway.labels" $ | nindent 4 }}
spec:
  http:
  - name: {{ .name }}
    backends:
    - serviceName: {{ .serviceName }}
      servicePort: {{ .servicePort }}
    websocket: {{ .websocket | default false }}
    match:
      hosts:
        - {{ print .subdomain "." $domain | quote }}
      paths:
      {{ .paths | toYaml | nindent 7 }}
      methods:
      {{ .methods | toYaml | nindent 7 }}
    plugins:
    {{- if .cors }}
    - name: cors
      enable: true
    {{- end }}
    {{- if .setUserHeader }}
    - name: kratos
      enable: true
      config:
        host: {{ print "http://" $apisixPlugins.kratos.serviceName  "." $namespace ".svc:" $apisixPlugins.kratos.servicePort | quote }}
        expose_user_data: true
        expose_user_id: true
        session_cookie_name: {{ $sessionCookie }}
    {{- end }}
    {{- if .regexUri }}
    - name: proxy-rewrite
      enable: true
      config:
        regex_uri: 
        {{ .regexUri | toYaml | nindent 9 }}
    {{- end }} 
---
{{- end }}
{{- end }}
