{{- $domain := .Values.domain -}}
{{- $devMode := .Values.certificates.devMode -}}
{{- if .Values.certificates.deploy -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hub-domains
  namespace: ingress-apisix
spec:
  dnsNames:
    {{- with .Values.routes }}
    {{- $usedHosts := "" -}}
    {{- range . }}
    {{- $currentHost := .host | default (printf "%s.%s" .subdomain $domain) | quote -}}
    {{- if not (contains $currentHost $usedHosts) }}
    - {{ $currentHost }}
    {{- $usedHosts = print $usedHosts $currentHost -}}
    {{- end }}
    {{- end }}
    {{- end }}
  issuerRef:
    kind: ClusterIssuer
    group: cert-manager.io
    {{- if $devMode }}
    name: selfsigned
    {{- else }}
    name: letsencrypt-prod
    {{- end }}
  {{- if $devMode }}
  isCA: true
  commonName: selfsigned-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  {{- end }}
  secretName: hub-certificates
  usages:
    - digital signature
    - key encipherment
  duration: 2160h # 90d
  renewBefore: 360h # 15d
{{- end }}
