apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-apisix-plugins
data:
  {{- $files := .Files }}
  {{- with $.Values.apisixPlugins.kratos.files}}
    {{- range . }}
      {{ (splitList "/" .) | last | nindent 2}}: |-
      {{ $.Files.Get . | nindent 8 }}
    {{- end }}
  {{- end }}

  {{- with $.Values.apisixPlugins.opa.files}}
    {{- range . }}
      {{ (splitList "/" .) | last | nindent 2}}: |-
        {{ $.Files.Get . | nindent 8 }}
    {{- end }}
  {{- end }}

  {{- with $.Values.apisixPlugins.graphql.files}}
    {{- range . }}
      {{ (splitList "/" .) | last | nindent 2}}: |-
        {{ $.Files.Get . | nindent 8 }}
    {{- end }}
  {{- end }}
