apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-custom-plugins
  labels:
    {{- include "hub-gateway.labels" $ | nindent 4 }}
data:
  {{- $files := .Files }}
  {{- range $key, $val := .Values.apisixPlugins }}
    {{- with $val.files}}
      {{- range . }}
        {{ (splitList "/" .) | last | nindent 2}}: |-
        {{ $.Files.Get . | nindent 8 }}
      {{- end }}
    {{- end }} 
  {{- end }}
