{{- if .Values.apisixPlugins.opa.s3.secretKey }}
{{- $s3 := .Values.apisixPlugins.opa.s3 -}}
{{- $namespace := .Values.hubNamespace -}}
apiVersion: v1
kind: Secret
metadata:
  name: opa-s3-creds
  namespace: {{ $namespace }}
  labels:
    {{- include "hub-gateway.labels" $ | nindent 4 }}
type: Opaque
data:
  AWS_REGION: {{ $s3.region| b64enc }} 
  AWS_BUCKET_URL: {{ $s3.bucketUrl | b64enc }} 
  AWS_ACCESS_KEY_ID: {{ $s3.accessKey | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ $s3.secretKey | b64enc }} 
{{- end }}
