{{- $namespace := .Values.hubNamespace -}}
{{- $apisixPlugins := .Values.apisixPlugins -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $apisixPlugins.opa.serviceName }}
  namespace: {{ $namespace }}
  labels:
    {{- include "hub-gateway.labels" $ | nindent 4 }}
    app: {{ $apisixPlugins.opa.serviceName }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $apisixPlugins.opa.serviceName }}
  template:
    metadata:
      labels:
        app: {{ $apisixPlugins.opa.serviceName }}
      name: {{ $apisixPlugins.opa.serviceName }}
    spec:
      containers:
      - name: opa
        image: {{ $apisixPlugins.opa.image }}
        envFrom:
        - secretRef:
            name: opa-s3-creds
        ports:
        - name: http
          containerPort: 8181
        args:
        - "run"
        - "--ignore=.*"
        - "--server"
        - "-c"
        - "/etc/opa/config.yaml"
        livenessProbe:
          httpGet:
            scheme: HTTP          
            port: {{ $apisixPlugins.opa.servicePort }}
          initialDelaySeconds: 5      
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health?bundle=true  # Include bundle activation in readiness
            scheme: HTTP
            port: {{ $apisixPlugins.opa.servicePort }}
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: config
          mountPath: /etc/opa/config.yaml
          subPath: config.yaml
      volumes:
        - name: config
          configMap:
            name: opa-config
