{{- if .Values.internalService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: apisix-gateway-internal
  labels:
    {{- include "hub-gateway.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9080
      protocol: TCP
      name: http
  selector:
    {{- include "hub-gateway.selectorLabels" $ | nindent 4 }}
{{- end }}
