{{- with .Values.secrets }}
{{- if .enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "svix.fullname" $ }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  SVIX_JWT_SECRET:  {{ .entries.jwtSecret | b64enc }}
  SVIX_DB_DSN: {{ .entries.dsn | b64enc }}
{{- end }}
{{- end }}
