apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hub-credentials.fullname" . }}
data:
  {{- with .Values.environment }}
  ORY_ADMIN_BASE_URL: {{ .oryAdminBaseUrl }}
  ORY_PUBLIC_BASE_URL: {{ .oryPublicBaseUrl }}
  PORT: {{ .port | quote }}
  {{- end }}
