apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hub-credentials.fullname" . }}
data:
  {{- with .Values.environment }}
  ORY_ADMIN_BASE_URL: {{ .oryAdminBaseUrl }}
  ORY_PUBLIC_BASE_URL: {{ .oryPublicBaseUrl }}
  PORT: {{ .port | quote }}
  KAFKA_BROKERS: {{ .kafkaBrokers | quote }}
  KAFKA_USERNAME: {{ required "must set kafka username" .kafkaUsername | quote }}
  KAFKA_SSL: {{ required "must set kafka ssl" .kafkaSsl | quote }}
  {{- end }}
  {{- end }}
