{{- with .Values.secrets }}
{{- if .enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hub-credentials.fullname" $ }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  ORY_AUTH_TOKEN: {{ .entries.oryAuthToken | b64enc }}
{{- end }}
{{- end }}