apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hub-treasuries.fullname" . }}
  labels:
    {{- include "hub-treasuries.labels" . | nindent 4 }}
  annotations:
    configmap.reloader.stakater.com/reload: {{ .Values.creditSheetName }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hub-treasuries.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hub-treasuries.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hub-treasuries.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "hub-treasuries.fullname" . }}
            - secretRef:
                name: {{ include "hub-treasuries.fullname" . }}
          ports:
            - name: http
              containerPort: {{ .Values.environment.port }}
              protocol: TCP
          volumeMounts:
            - name: fireblocks-privkey
              mountPath: /app/secret.key
              subPath: secret.key
              readOnly: true
            - name: credit-sheet
              mountPath: /app/credit-sheet.toml
              subPath: credit-sheet.toml
              readOnly: true
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: fireblocks-privkey
          secret:
            secretName: {{ print (include "hub-treasuries.fullname" .) "-privkey" }}
            optional: false
        - name: credit-sheet
          configMap:
            name: {{ .Values.creditSheetName }}
            optional: false
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
