apiVersion: v1
kind: Service
metadata:
  name: {{ include "hub-treasuries.fullname" . }}
  labels:
    {{- include "hub-treasuries.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hub-treasuries.selectorLabels" . | nindent 4 }}
{{- if and (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") (.Values.serviceMonitor.enabled) }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "hub-treasuries.fullname" . }}
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "hub-treasuries.labels" . | nindent 4 }}
{{- with .Values.serviceMonitor.labels }}
  {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  endpoints:
  - path: /metrics
    port: http
    scheme: {{ .Values.serviceMonitor.scheme }}
    interval: {{ .Values.serviceMonitor.scrapeInterval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hub-treasuries.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}
