apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hub-analytics.fullname" . }}
data:
  {{- with .Values.environment }}
  RUST_LOG: {{ .logLevel }}
  KAFKA_BROKERS: {{ required "must set kafka brokers" .kafkaBrokers | quote }}
  KAFKA_SSL: {{ default "false" .kafkaSsl | quote }}
  KAFKA_USERNAME: {{ required "must set kafka username" .kafkaUsername | quote }}
  DB_URL: {{ required "must set influxdb url" .influxdbUrl | quote }}
  DB_BUCKET: {{ required "must set influxdb bucket" .influxdbBucket | quote }}
  DB_ORG: {{ required "must set influxdb org" .influxdbOrg | quote }}
  {{- end }}
