apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hub-webhooks.fullname" . }}
data:
  {{- with .Values.environment }}
  PORT: {{ .port | quote }}
  KAFKA_BROKERS: {{ required "must set kafka brokers" .kafkaBrokers | quote }}
  KAFKA_USERNAME: {{ required "must set kafka username" .kafkaUsername | quote }}
  KAFKA_SSL: {{ required "must set kafka ssl" .kafkaSsl | quote }}
  SVIX_BASE_URL: {{ required "must set svix base url" .svixBaseUrl | quote }}
  {{- end }}
