{{- with .Values.secrets }}
{{- if .enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hub-webhooks.fullname" $ }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  SVIX_AUTH_TOKEN:  {{ .entries.svixAuthToken | b64enc }}
  DATABASE_URL: {{ .entries.databaseUrl | b64enc }}
  KAFKA_PASSWORD: {{ .entries.kafkaPassword | b64enc }}
{{- end }}
{{- end }}
