{{- with .Values.secrets }}
{{- if .enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opa.fullname" $ }}
  annotations:
    "helm.sh/hook": pre-install
  labels:
    {{- include "opa.labels" $ | nindent 4 }}
type: Opaque
data:
  AWS_REGION: {{ required "must set S3 bucket region" .entries.s3Region | b64enc }} 
  AWS_BUCKET_URL: {{ required "must set S3 bucket Url" .entries.s3BucketUrl | b64enc }} 
  AWS_ACCESS_KEY_ID: {{ required "must set S3 access key" .entries.s3AccessKey | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ required "must set S3 secret key" .entries.s3SecretKey | b64enc }} 
{{- end }}
{{- end }}
