apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hub-nfts.fullname" . }}
data:
  {{- with .Values.environment }}
  PORT: {{ .port | quote }}
  KAFKA_BROKERS: {{ required "must set kafka brokers" .kafkaBrokers | quote }}
  KAFKA_USERNAME: {{ required "must set kafka username" .kafkaUsername | quote }}
  KAFKA_SSL: {{ required "must set kafka ssl" .kafkaSsl | quote }}
  IPFS_ENDPOINT: {{ required "must set ipfs endpoint" .ipfsEndpoint | quote }}
  NFT_STORAGE_API_ENDPOINT: {{ required "must set nft storage api endpoint" .nftStorageApiEndpoint | quote }}
  CREDIT_SHEET: /app/credit-sheet.toml
  ASSET_CDN: {{ .assetCdn | quote }}
  {{- end }}
