apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hub-nfts.fullname" . }}
data:
  {{- with .Values.environment }}
  PORT: {{ .port | quote }}
  KAFKA_BROKERS: {{ required "must set kafka brokers" .kafkaBrokers | quote }}
  KAFKA_USERNAME: {{ required "must set kafka username" .kafkaUsername | quote }}
  KAFKA_SSL: {{ required "must set kafka ssl" .kafkaSsl | quote }}
  HUB_UPLOADS_API_ENDPOINT: {{ .hubUploadsApiEndpoint | quote }}
  CREDIT_SHEET: /app/credit-sheet.toml
  ASSET_CDN: {{ .assetCdn | quote }}
  REDIS_URL: {{ required "must set redis url" .redisUrl | quote }}
  {{- end }}
