apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hub-nfts-polygon.fullname" . }}
data:
  {{- with .Values.environment }}
  POLYGON_EDITION_CONTRACT: {{ required "must set polygon edition contract address" .polygonEditionContractAddress | quote }}
  KAFKA_BROKERS: {{ required "must set kafka brokers" .kafkaBrokers | quote }}
  KAFKA_USERNAME: {{ required "must set kafka username" .kafkaUsername | quote }}
  KAFKA_SSL: {{ required "must set kafka ssl" .kafkaSsl | quote }}
  {{- end }}
