{{- if .Values.indexer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hub-nfts-polygon.fullname" . }}-indexer
  labels:
    {{- include "hub-nfts-polygon.labels" . | nindent 4 }}
    app.kubernetes.io/component: indexer
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hub-nfts-polygon.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: indexer
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hub-nfts-polygon.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: indexer
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hub-nfts-polygon.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: indexer
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- with .Values.indexer.image }}
          image: "{{ .repository }}:{{ .tag }}"
          imagePullPolicy: {{ .pullPolicy }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "hub-nfts-polygon.fullname" . }}
            - secretRef:
                name: {{ include "hub-nfts-polygon.fullname" . }}
          ports:
            - name: http
              containerPort: {{ .Values.environment.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}