{{- with .Values.secrets }}
{{- if .enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hub-nfts-polygon.fullname" $ }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  DATABASE_URL: {{ required "must set databaseUrl" .entries.databaseUrl | b64enc }}
  KAFKA_PASSWORD: {{ .entries.kafkaPassword | b64enc }}
  POLYGON_RPC_ENDPOINT: {{ required "must set RPC endpoint .polygonEndpoint" .entries.polygonEndpoint | b64enc }}
  {{- if .Values.indexer.enabled }}
  WEBHOOK_SIGNING_KEY: {{ required "must set webhook signing key" .entries.webhookSigningKey | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
