apiVersion: v1
kind: Service
metadata:
  name: {{ include "hub-nfts-polygon.fullname" . }}
  labels:
    {{- include "hub-nfts-polygon.labels" . | nindent 4 }}
    app.kubernetes.io/component: indexer
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hub-nfts-polygon.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: indexer
