apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hub-orgs.fullname" . }}
data:
  {{- with .Values.environment }}
  ORY_BASE_URL: {{ .oryBaseUrl }}
  PORT: {{ .port | quote }}
  KAFKA_BROKERS: {{ required "must set kafka brokers" .kafkaBrokers | quote }}
  SVIX_BASE_URL: {{ required "must set svix base url" .svixBaseUrl | quote }}
  {{- end }}