{{- with .Values.secrets }}
{{- if .enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hub-orgs.fullname" $ }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  DATABASE_URL: {{ .entries.databaseUrl | b64enc }}
  ORY_AUTH_TOKEN: {{ .entries.oryAuthToken | b64enc }}
{{- end }}
{{- end }}