cubes:
  - name: collections
    sql_table: public.collections
    data_source: default

    joins:
      - name: projects
        sql: "{CUBE}.project_id = {projects}.id"
        relationship: many_to_one

    dimensions:
      - name: id
        sql: id
        type: string
        primary_key: true

      - name: project_id
        sql: project_id
        type: string

      - name: blockchain
        sql: blockchain
        type: string

      - name: timestamp
        sql: timestamp
        type: time

    measures:
      - name: count
        type: count

    pre_aggregations:
