cubes:
  - name: mints
    sql_table: public.mints
    data_source: default

    joins:
      - name: collections
        sql: "{CUBE}.collection_id = {collections}.id"
        relationship: many_to_one

      - name: projects
        sql: "{CUBE}.project_id = {projects}.id"
        relationship: many_to_one

    dimensions:
      - name: id
        sql: id
        type: string
        primary_key: true

      - name: collection_id
        sql: collection_id
        type: string

      - name: project_id
        sql: project_id
        type: string

      - name: timestamp
        sql: timestamp
        type: time

    measures:
      - name: count
        type: count

    pre_aggregations:
