{{- $organizationName  := .Values.organization -}}
{{- range .Values.runners }}
  {{- $runner := . -}}
  {{- range .architectures }}
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: {{ $runner.name }}-{{ . }}
  namespace: actions-runner-system
  labels:
    arch: {{ . }}
    organization: {{ $organizationName }}
spec:
  replicas: {{ $runner.replicas.min }}
  template:
    spec:
      repository: {{ $organizationName }}/{{ $runner.repository }}
      labels:
      - {{ . }}
      {{- if eq . "amd64" }}
      - self-hosted
      {{- end }}
      nodeSelector:
        kubernetes.io/arch: {{ . }}
      tolerations:
      {{- if $runner.extraTolerations }}
      {{ toYaml $runner.extraTolerations | indent 8 }}
      {{- end }}
      - key: "kubernetes.io/arch"
        operator: "Equal"
        value: {{ . }}
        effect: "NoSchedule"
      topologySpreadConstraints:
      {{- if $runner.extraConstraints }}
      {{ toYaml $runner.extraConstraints | indent 8 }}
      {{- end }}
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            arch: {{ . }}
            organization: {{ $organizationName }}
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: {{ $runner.name }}-{{ . }}
spec:
  scaleTargetRef:
    kind: RunnerDeployment
    name: {{ $runner.name }}-{{ . }}
  minReplicas: {{ $runner.replicas.min }}
  maxReplicas: {{ $runner.replicas.max }}
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - {{ $organizationName }}/{{ $runner.repository }}
  {{- end }}
{{- end }}
