apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hub-ui.fullname" . }}
data:
  {{- with .Values.environment }}
  KRATOS_ENDPOINT: {{ .kratosPublicEndpoint | quote }}
  PORT: {{ .port | quote }}
  {{- end }}
