{{- with .Values.secrets }}
{{- if .enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hub-ui.fullname" $ }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  NFT_STORAGE_TOKEN: {{ required "must set nft storage token" .entries.nftStorageToken | b64enc }}
{{- end }}
{{- end }}
