{{- $files := .Files }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: keto-namespaces
  labels:
    {{- include "hub-permissions.labels" $ | nindent 4 }}
data:
    {{- with .Values.customNamespaces.files}}
      {{- range . }}
        {{ (splitList "/" .) | last | nindent 2}}: |-
        {{ $.Files.Get . | nindent 8 }}
      {{- end }}
    {{- end }} 
