{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "hub-permissions.fullname" . }}
  labels:
    {{- include "hub-permissions.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "hub-permissions.selectorLabels" . | nindent 8 }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: redpanda
      ports:
        - port: 9092
          protocol: TCP
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: keto
      ports:
        - port: 4466
          protocol: TCP
        - port: 4467
          protocol: TCP
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: node-local-dns
      ports:
        - port: 53
          protocol: UDP
{{- if .Values.networkPolicies.extraEgress }}
{{ toYaml .Values.networkPolicies.extraEgress | indent 4 }}
{{- end }}
{{- if .Values.networkPolicies.extraIngress }}
  ingress:
{{ toYaml .Values.networkPolicies.extraIngress | indent 4 }}
{{- end }}
  policyTypes:
{{- if .Values.networkPolicies.extraIngress }}
    - Ingress
{{- end }}
    - Egress
{{- end }}
