apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hub-identities.fullname" . }}
data:
  KRATOS_ADMIN_ENDPOINT: {{ .Values.environment.kratosAdminEndpoint }}
  PORT: "{{ .Values.environment.port }}"