{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "hub-identities.fullname" . }}
  labels:
    {{- include "hub-identities.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "hub-identities.selectorLabels" . | nindent 8 }}
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 192.168.0.0/16
              - 172.16.0.0/20
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: redpanda
      ports:
        - port: 9093
          protocol: TCP
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: kratos
      ports:
        - port: 4434
          protocol: TCP
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: node-local-dns
      ports:
        - port: 53
          protocol: UDP
{{- if .Values.networkPolicies.extraEgress }}
{{ toYaml .Values.networkPolicies.extraEgress | indent 4 }}
{{- end }}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-apisix
          podSelector:
            matchLabels:
              app.kubernetes.io/name: apisix
      ports:
        - port: {{ .Values.environment.port }}
          protocol: TCP
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: router
      ports:
        - port: {{ .Values.environment.port }}
          protocol: TCP
{{- if .Values.networkPolicies.extraIngress }}
{{ toYaml .Values.networkPolicies.extraIngress | indent 4 }}
{{- end }}
  policyTypes:
    - Ingress
    - Egress
{{- end }}
